### ISSUE TITLE
Have coverage be based on all of the files that match the coverage files globs, not just the ones imported by tests

### ISSUE THREAD

**Issue by internettrans** [CanopyTax/node-jspm-jasmine#12]

**Comment by m-a-r-c-e-l-i-n-o** [comment]
@joeldenning Would be as simple as merging the globs [here](https://github.com/CanopyTax/node-jspm-jasmine/blob/master/src/node-jspm-jasmine.js#L147), but the [helper loop](https://github.com/CanopyTax/node-jspm-jasmine/blob/master/src/node-jspm-jasmine.js#L120) makes that redundant. Should probably create a synchronous `importCoverageFiles` function right around [here](https://github.com/CanopyTax/node-jspm-jasmine/blob/master/src/node-jspm-jasmine.js#L103) and import all those files before moving on to `importTestFiles`.
