### ISSUE TITLE
Callback when tests are done.

### ISSUE THREAD

**Issue by henebb** [CanopyTax/node-jspm-jasmine#40]
Right now there's only an error callback in the JS API (runTests). It'd be nice to have a callback when all tests are done, regardless if it was successful or not. Or perhaps just add an additional success callback as well. This is especially useful when using the API together with e.g. gulp.

Thanks for a great job!

**Comment by internettrans** [comment]
Good idea. I'm thinking the best way to do this would be to just change the errCallback to be a more traditional [node errback](http://fredkschott.com/post/2014/03/understanding-error-first-callbacks-in-node-js/). I believe that doing so will be mostly backwards compatible, unless someone is not checking the arguments to the errCallback to see if there is an actual error.

I guess the other option would be just to add a successCallback as a third argument to `runTests`.

I will work on this later today.

**Comment by internettrans** [comment]
Released as 3.0.0
