### ISSUE TITLE
Does not exit cleanly after a successful run

### ISSUE THREAD

**Issue by CxRes** [CanopyTax/node-jspm-jasmine#43]
After a successful run from the cli, the program exits with status code 1. This is happening because `safeExit()` with jasmine exit strategy is not created and passed to the `errCallback()` in `finishTestRun()`.

I'll make a PR that fixes this bug....

**Comment by CxRes** [comment]
After you accept the above PR (so that I know you are there :)) I would also like to move the `errCallback()` in `runTest()` from `cli.js` to `node-jspm-jasmine.js` and set it as a default argument to the export function. This way anyone using a `runTests()` can benefit from the `safeExit()` logic.

**Comment by internettrans** [comment]
Thanks for reporting this and fixing it! Released your fix as [v3.0.1](https://github.com/CanopyTax/node-jspm-jasmine/releases/tag/v3.0.1).
